"""
Main execution script for Football Video Analysis System.

This script orchestrates the complete pipeline for analyzing football video:
1. Load and resize video frames to standard resolution
2. Run multi-object tracking on all frames
3. Train team assigner on player jersey colors (warm-up phase)
4. For each frame:
   - Detect pitch keypoints and compute homography
   - Assign teams to players based on jersey color
   - Transform player/ball positions to tactical field coordinates
   - Draw annotations and create tactical minimap
   - Overlay minimap on main frame
   - Write annotated frame to output video

Input: Preprocessed football video
Output: Annotated video with player tracking, team classification, and tactical minimap
"""

import cv2
from utils.video_utils import read_video
from tracking.tracker import Tracker
from visualization.renderer import Renderer
from team_assignment.team_assigner import TeamAssigner
from transformation.transformer import Transformer

# ============================================================================
# Configuration - Update these paths for your input/output
# ============================================================================

# Path to input football video file
INPUT_VIDEO = "data/input/match.mp4"

# Path where final annotated video will be saved
OUTPUT_VIDEO = "data/output/final_output.mp4"

# Path to trained YOLOv8 detection model (for player/ball detection)
# Generated by train/train_player.py
PLAYER_MODEL_PATH = "runs\\detect\\train-2\\weights\\best.pt"

# Path to trained YOLOv8 pose model (for field keypoint detection)
# Generated by train/train_pitch.py
PITCH_MODEL_PATH = "runs/pose/train/weights/best.pt"


def main():
    """
    Main execution pipeline for football video analysis.
    
    Pipeline stages:
    1. Video I/O: Load input video and prepare output writer
    2. Detection & Tracking: Run YOLO + ByteTrack on all frames
    3. Team Training: Collect jersey colors and train K-Means
    4. Frame Processing:
       - Detect field keypoints and compute homography
       - Classify players to teams
       - Transform coordinates to tactical field view
       - Render annotations and minimap
       - Write output frame
    """
    
    # ========================================================================
    # Stage 1: Load Input Video and Normalize Resolution
    # ========================================================================
    print("[INFO] Loading input video...")
    frames, fps = read_video(INPUT_VIDEO)
    
    # Resize all frames to standard 1920x1080 resolution for consistency
    # This ensures homography matrix and tactical minimap are calibrated correctly
    resized_frames = []
    for frame in frames:
        frame = cv2.resize(frame, (1920, 1080))
        resized_frames.append(frame)
    frames = resized_frames
    print(f"[INFO] Loaded {len(frames)} frames at {fps} FPS")

    # ========================================================================
    # Prepare Video Output Writer
    # ========================================================================
    height, width = frames[0].shape[:2]
    fourcc = cv2.VideoWriter_fourcc(*'mp4v')  # MP4 codec
    video_writer = cv2.VideoWriter(OUTPUT_VIDEO, fourcc, fps, (width, height))

    # ========================================================================
    # Stage 2: Initialize Core Modules
    # ========================================================================
    print("[INFO] Initializing modules...")
    tracker = Tracker(PLAYER_MODEL_PATH)                    # Detection + tracking
    renderer = Renderer()                                    # Visualization
    team_assigner = TeamAssigner()                          # Team classification
    transformer = Transformer(PITCH_MODEL_PATH)            # Field transformation

    # ========================================================================
    # Stage 3: Detection and Multi-Object Tracking
    # ========================================================================
    print("[INFO] Running detection and tracking on all frames...")
    tracks = tracker.detect_and_track(frames)
    print(f"[INFO] Detection and tracking completed")

    # ========================================================================
    # Stage 4: Team Assigner Warm-up Phase
    # ========================================================================
    # The team assigner needs to learn the two dominant jersey colors
    # Collect colors from first 50 frames (or entire video if shorter)
    print("[INFO] Warm-up Phase for Team Assigner - collecting jersey colors...")
    NUM_FRAMES_TO_COLLECT = min(50, len(frames))
    for idx in range(NUM_FRAMES_TO_COLLECT):
        # Extract player bounding boxes (class_id == 2 is player)
        player_bboxes = [det["bbox"] for det in tracks[idx] if det["class_id"] == 2]
        # Accumulate jersey colors for K-Means training
        team_assigner.accumulate_frame_colors(frames[idx], player_bboxes)
    
    # Train K-Means on collected colors to identify 2 team clusters
    team_assigner.fit()
    print(f"[INFO] Team assigner trained on {NUM_FRAMES_TO_COLLECT} frames")

    # ========================================================================
    # Stage 5: Main Processing Loop - Frame-by-Frame Analysis
    # ========================================================================
    print("[INFO] Executing frame processing: transformation, team assignment, and visualization...")
    
    for frame_idx, (frame, detections) in enumerate(zip(frames, tracks)):
        # Create a copy to avoid modifying original frame
        frame = frame.copy()

        # --- Detect Pitch Keypoints and Compute Homography ---
        # Detect football field markings using pose model
        keypoints_object = transformer.detect_keypoints(frame)
        
        # Compute perspective transformation matrix (camera view → tactical field)
        homography_matrix = transformer.get_homography_matrix(keypoints_object)

        # --- Process Each Detection in Frame ---
        for det in detections:
            class_id = det["class_id"]

            # PLAYER CLASS (class_id == 2): Assign team color
            if class_id == 2:
                team_id = team_assigner.get_team(frame, det["bbox"], det["track_id"])
                if team_id == -1:
                    # Failed to classify - mark as referee
                    det["class_id"] = 3
                else:
                    # Successfully classified - add team_id to detection
                    det["team_id"] = team_id

            # ALL OBJECTS: Transform camera coordinates to tactical field coordinates
            if class_id in [0, 1, 2, 3]:  # Ball, goalkeeper, player, referee
                is_ball = (class_id == 0)
                # Transform bounding box center/foot position to minimap coordinates
                transformed_coords = transformer.transform_position(
                    homography_matrix, 
                    det["bbox"], 
                    is_ball=is_ball
                )
                if transformed_coords is not None:
                    det["transformed_coords"] = transformed_coords

        # --- Render Annotations on Main Frame ---
        # Draw detection boxes and track IDs
        frame = renderer.draw_tracks(frame, detections)
        
        # Draw detected pitch keypoints for visualization
        frame = renderer.draw_keypoints(frame, keypoints_object)

        # --- Create and Overlay Tactical Minimap ---
        # Generate bird's-eye tactical view of field with player positions
        tactical_pitch = renderer.draw_tactical_pitch(detections)
        
        # Overlay minimap in bottom-right corner with 75% opacity
        frame = renderer.add_minimap_to_frame(frame, tactical_pitch, opacity=0.75)

        # --- Write Annotated Frame to Output Video ---
        video_writer.write(frame)

        # --- Progress Reporting (every 25 frames) ---
        if frame_idx % 25 == 0 or frame_idx == len(frames) - 1:
            progress = (frame_idx + 1) * 100 / len(frames)
            print(f"\r[INFO] Processing Progress: {progress:.2f}%", end="", flush=True)

    # ========================================================================
    # Stage 6: Finalization
    # ========================================================================
    video_writer.release()
    print("\n[DONE] Analysis complete! Final video saved to:", OUTPUT_VIDEO)


if __name__ == "__main__":
    main()